package hltb

const (
	PlatformAll            = ""
	PlatformPC             = "PC"
	PlatformEmulated       = "Emulated"
	PlatformNES            = "NES"
	PlatformSNES           = "Super Nintendo"
	PlatformNintendoDS     = "Nintendo DS"
	PlatformNintendo3DS    = "Nintendo 3DS"
	PlatformNintendo64     = "Nintendo 64"
	PlatformGameCube       = "Nintendo GameCube"
	PlatformNintendoSwitch = "Nintendo Switch"
	PlatformGameBoy        = "Game Boy"
	PlatformGameBoyColor   = "Game Boy Color"
	PlatformGameBoyAdvance = "Game Boy Advance"
	PlatformPlayStation    = "PlayStation"
	PlatformPlayStation2   = "PlayStation 2"
	PlatformPlayStation3   = "PlayStation 3"
	PlatformPlayStation4   = "PlayStation 4"
	PlatformPlayStation5   = "PlayStation 5"
	PlatformPSVita         = "PlayStation Vita"
	PlatformPSP            = "PlayStation Portable"
	PlatformWii            = "Wii"
	PlatformWiiU           = "Wii U"
	PlatformXbox           = "Xbox"
	PlatformXbox360        = "Xbox 360"
	PlatformXboxOne        = "Xbox One"
	PlatformXboxSeriesXS   = "Xbox Series X/S"

	ModifierNone      = ""
	ModifierHideDLC   = "hide_dlc"
	ModifierOnlyDLC   = "only_dlc"
	ModifierOnlyMods  = "only_mods"
	ModifierOnlyHacks = "only_hacks"
)
